server:
  forward-headers-strategy: native
  error:
    include-message: always
  port: 8080

spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/post
      auto-index-creation: true
#  r2dbc:
#    url: r2dbc:mysql://127.0.0.1:3306/post_webflux?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
#    username: root
#    password:
#    pool:
#      max-size: 100
#      validation-query: SELECT 1

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: always

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
